{% set name = "deepchecks" %}
{% set version = "0.7.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepchecks-{{ version }}.tar.gz
  sha256: d8f3cfe98853af1c2035584c435d5f3e82cf976bc8ab7398416f5a7862bef284

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - category_encoders >=2.3.0
    - dataclasses >=0.6
    - ipykernel >=5.3.0
    - ipython >=7.15.0,<8
    - ipywidgets >=7.6.5
    - jsonpickle >=2.1.0
    - matplotlib-base >=3.3.3
    - numpy >=1.19
    - pandas >=1.1.5
    - plotly >=5.5.0,<5.6
    - pynomaly >=0.3.3
    - python >=3.6
    - scikit-learn >=0.24.2
    - scipy >=1.4.1
    - statsmodels >=0.11.0
    - tqdm >=4.62.3
    - typing-extensions >=3.7.4.3

test:
  imports:
    - deepchecks
    - deepchecks.analytics
    - deepchecks.core
    - deepchecks.core.check_utils
    - deepchecks.core.serialization
    - deepchecks.core.serialization.check_failure
    - deepchecks.core.serialization.check_result
    - deepchecks.core.serialization.dataframe 
    - deepchecks.core.serialization.suite_result
    - deepchecks.datasets
    - deepchecks.tabular
    - deepchecks.tabular.checks
    - deepchecks.tabular.checks.data_integrity
    - deepchecks.tabular.checks.distribution
    - deepchecks.tabular.checks.methodology
    - deepchecks.tabular.checks.model_evaluation
    - deepchecks.tabular.checks.overview
    - deepchecks.tabular.checks.performance
    - deepchecks.tabular.checks.train_test_validation
    - deepchecks.tabular.datasets
    - deepchecks.tabular.datasets.classification
    - deepchecks.tabular.datasets.regression
    - deepchecks.tabular.suites
    - deepchecks.tabular.utils
    - deepchecks.utils
    - deepchecks.utils.distribution
    - deepchecks.utils.performance

  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepchecks/deepchecks
  summary: Test Suites for Validating ML Models & Data
  doc_url: https://docs.deepchecks.com/
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
