{% set name = "deepchecks" %}
{% set version = "0.9.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/deepchecks-{{ version }}.tar.gz
  sha256: 20f73614677b6f916f3556bfb1e8ad5184ffefea3a33520780b4fefa3a81290f

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - category_encoders >=2.3.0
    - dataclasses >=0.6
    - importlib_resources >=1.3
    - importlib_metadata >=1.4
    - ipykernel >=5.3.0
    - ipython >=7.15.0,<8
    - ipywidgets >=7.6.5,<8
    - jsonpickle >=2
    - matplotlib-base >=3.3.4
    - numpy >=1.19
    - pandas >=1.1.5
    - plotly >=5.5.0,<5.6
    - pynomaly >=0.3.3
    - python >=3.6
    - scikit-learn >=0.23.2
    - scipy >=1.4.1
    - statsmodels >=0.11.0
    - tqdm >=4.62.3
    - typing-extensions >=3.7.4.3

test:
  imports:
    - deepchecks
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/deepchecks/deepchecks
  summary: Test Suites for Validating ML Models & Data
  doc_url: https://docs.deepchecks.com/
  license: AGPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
